name: Java CI/CD with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn clean install
          mkdir artifacts && cp target/*.jar artifacts
          cd artifacts && ls

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-action-artifact
          path: artifacts

      # Step to login to GitHub Container Registry (GHCR)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # GitHub username (actor)
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub token provided by Actions

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push image to GHCR
      - name: Build and push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/spring-boot-github-action-demo:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest  # Change this as needed for AWS EC2

    steps:
      - name: Login to GitHub Container Registry on EC2
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Pull Image from GHCR
        run: sudo docker pull ghcr.io/${{ github.repository }}/spring-boot-github-action-demo:latest

      - name: Delete old container
        run: sudo docker rm -f spring-boot-app-container || true  # Ensure no error if container doesn't exist

      - name: Run Docker Image
        run: sudo docker run -d -p 8080:8080 --name spring-boot-app-container ghcr.io/${{ github.repository }}/spring-boot-github-action-demo:latest
